baseurl = "https://frosforever.github.io"
languageCode = "en-us"
title = "Thoughts and notes"
theme = "hyde-x"
MetaDataFormat = "toml"

[author]
    name = "Yosef Fertel"

[permalinks]
    # Change the permalink format for the 'post' content type.
    post = "/blog/:year/:month/:day/:title/"

[indexes]
    category = "categories"

[params]
    # Select a syntax highight.
    highlight = "solarized_dark"

    # Tagline to display under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Thoughts and notes"

    # Sidebar social links.
    github = "https://github.com/frosforever"
    bitbucket = ""
    linkedin = "https://www.linkedin.com/in/yfertel"
    googleplus = ""
    facebook = ""
    twitter = ""
